consul:
 image: terbooter/consul
# build: .
 net: "host"
 command: ["/start.sh"]
 restart: always
 env_file: .dockerenv

registrator:
 image: gliderlabs/registrator:latest
 net: "host"
 volumes:
   - /var/run/docker.sock:/tmp/docker.sock
 command: ["consul://172.17.0.1:8500"]
 restart: always